language: rust
rust:
  - 1.33.0
  - beta
env:
  global:
    - TARGET_BUILD=thumbv7em-none-eabi
    - RUSTFLAGS="--deny warnings"

install:
  - rustup target add $TARGET_BUILD
  - rustup component add rustfmt

stages:
  - test
  - name: deploy
    if: branch = master AND type = push

jobs:
  include:
    - stage: test
      script:
        - cargo fmt --all -- --check
        - cargo check --target $TARGET_BUILD
        - cd rubble-nrf52 && cargo check --features="52810" && cargo check --features="52832" && cargo check --features="52840" && cd ..
        - cd rubble-demo && cargo check --target $TARGET_BUILD --no-default-features
    - stage: deploy
      script:
        - cargo doc --no-deps
        - echo "<meta http-equiv=refresh content=0;url=rubble/index.html>" > target/$TARGET_BUILD/doc/index.html
        - sudo pip install ghp-import
        - ghp-import -n target/$TARGET_BUILD/doc
        - git push -qf https://${GH_TOKEN}@github.com/jonas-schievink/rubble.git gh-pages

notifications:
  email:
    on_success: never
